- name: Check VMID for each VM and fetch if necessary
  block:
    - name: Fetch next available VMID from Proxmox if not already provided
      uri:
        url: "{{ proxmox_api_url }}/cluster/nextid"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        return_content: true
        validate_certs: no
      register: next_vmid_response
      when: vm_item.vmid is undefined or vm_item.vmid == ''

    - name: Assign fetched VMID to VM
      set_fact:
        vms: >-
          {{
            vms | map(attribute='name') | zip(vms | map('combine', {
              'vmid': (vm_item.vmid | default(next_vmid_response.json.data))
            })) | map('combine') | list
          }}
      when: vm_item.vmid is undefined or vm_item.vmid == ''
  loop: "{{ vms }}"
  loop_control:
    loop_var: "vm_item"
