---
- name: Get next available VMID if not explicitly provided
  uri:
    url: "{{ proxmox_api_url }}/cluster/nextid"
    method: GET
    headers:
      Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
    return_content: yes
    validate_certs: no  # Change to yes in production environments
  register: next_vmid_result
  when: item.vmid is not defined or item.vmid == ''
  loop: "{{ vms }}"
  loop_control:
    loop_var: item
  delegate_to: localhost

- name: Set VMID from API if not already provided
  set_fact:
    vms: "{{ vms | map('combine', {'vmid': (item.vmid | default(next_vmid_result.results[loop.index0].json.data))}) | list }}"
  loop: "{{ vms }}"
  loop_control:
    loop_var: item
